github_token: "your_github_personal_access_token"
subscriptions:
  - "owner/repo1"
  - "owner/repo2"
notification_channels:
  - "email"
  - "slack"
email_settings:
  smtp_server: "smtp.example.com"
  smtp_port: 587
  sender: "sentinel@example.com"
  recipients:
    - "user1@example.com"
slack_webhook: "https://hooks.slack.com/services/xxx/yyy/zzz"
